# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/999_Testing.ipynb.

# %% auto 0
__all__ = ['logger', 'true_after']

# %% ../nbs/999_Testing.ipynb 1
from typing import *

from datetime import datetime, timedelta
import time

import fast_kafka_api.logger

fast_kafka_api.logger.should_supress_timestamps = True
from .logger import get_logger

# %% ../nbs/999_Testing.ipynb 2
logger = get_logger(__name__)

# %% ../nbs/999_Testing.ipynb 3
logger = get_logger(__name__, level=0)

# %% ../nbs/999_Testing.ipynb 5
def true_after(seconds: float):
    """Function returning True after a given number of seconds"""
    t = datetime.now()

    def _true_after(seconds=seconds, t=t):
        return (datetime.now() - t) > timedelta(seconds=seconds)

    return _true_after
