from enum import Enum

ContentType = str


class ContentTypes(str, Enum):
    """A class to represent content types.

    Attributes:
        text : content type for plain text
        json : content type for JSON data
    !!! note

        The above docstring is autogenerated by docstring-gen library (https://docstring-gen.airt.ai)
    """

    text = "text/plain"
    json = "application/json"
