# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/027_App_Description_Validator.ipynb.

# %% auto 0
__all__ = ['logger', 'validate_app_description']

# %% ../../nbs/027_App_Description_Validator.ipynb 1
from typing import *
import time

from yaspin import yaspin
from .._components.logger import get_logger

# %% ../../nbs/027_App_Description_Validator.ipynb 3
logger = get_logger(__name__)

# %% ../../nbs/027_App_Description_Validator.ipynb 5
def validate_app_description(description: str) -> None:
    """Validate the user's application description

    If the description is unrelated to FastKafka or contains insensitive/inappropriate language, show an error
    message and exit the program. Otherwise, display the success message in the terminal.

    Args:
        description: User's application description
    """
    # TODO: Implement the actual functionality
    print("✨  Generating a new FastKafka application!")
    time.sleep(1)

    with yaspin(
        text="Validating the application description...", color="cyan", spinner="clock"
    ) as sp:
        time.sleep(2)
        sp.text = ""
        sp.ok(" ✔ Application description validated")
