name: Deploy Docs to GitHub Pages

on:
  workflow_dispatch: null
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: |
          set -ux
          uv pip install --system -e .[dev]
          uv pip uninstall --system email-validator # This is to fix broken link in docs
      - run: cd docs && python docs.py build
      - run: echo "VERSION=$(python3 -c 'from importlib.metadata import version; print(".".join(version("faststream").split(".")[:2]))')" >> $GITHUB_ENV
      - run: echo "IS_RC=$(python3 -c 'from importlib.metadata import version; print("rc" in version("faststream"))')" >> $GITHUB_ENV
      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - run: echo $VERSION
      - run: echo $IS_RC
      - run: |
          if [ "$IS_RC" == "False" ]; then
            cd docs && mike deploy -F mkdocs.yml --update-aliases $VERSION latest
            mike set-default --push --allow-empty -F mkdocs.yml latest
          else
            cd docs && mike deploy --push -F mkdocs.yml --update-aliases $VERSION
          fi
